server:
  port: 8082

spring:
  application:
    name: library-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/realms/logos-realm/protocol/openid-connect/certs
  
  datasource:
    # A MESMA URL QUE FUNCIONOU NO AI-PROCESSOR (Com SSL e ChannelBinding se necessário)
    url: jdbc:postgresql://ep-round-mud-af0br44i-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_AI1n4JKxGzut
    driver-class-name: org.postgresql.Driver
    
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update # Pode manter update para ele criar a tabela se não existir
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false

  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092 # Mesma do ai-processor
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="PA57SZCCZEALKVXR" password="cfltajgqBg76kNMVtyBpFhl59XMZeJIPT7il3f3CE69xQNR+Wh8F9eJyUPQBI9Qw";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    gcp:
      storage:
        enabled: true
      credentials:
        location: file:credentials.json 

management:
  tracing:
    sampling:
      probability: 1.0 # Em produção seria 0.1, mas em Dev queremos ver TUDO
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

gcp:
  storage:
    bucket-name: ogos-knowledge-base

routes:
        # Rota 1: Library Service (Leitura + Perfil)
        - id: library-service
          uri: http://localhost:8082
          predicates:
            # ADICIONE AQUI: /api/users/**
            - Path=/api/library/**, /api/galaxy/**, /api/users/**