version: '3.8'

services:
  # --- 1. ORACLE DATABASE (Relacional) ---
  # Usamos a versão XE (Express Edition) otimizada para dev
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle_password # Senha do sys e system
      APP_USER: appuser               # Cria usuário automático
      APP_USER_PASSWORD: apppassword  # Senha do usuário
    volumes:
      - oracle_data:/opt/oracle/oradata

  # --- 2. MinIO (S3 Local - Object Storage) ---
  # Armazena os PDFs e Imagens
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API (Backend usa essa)
      - "9001:9001" # Console UI (Você usa essa no navegador)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # --- 3. REDIS STACK (Cache + Vetor + UI) ---
  # Para FinOps (Cache Semântico) e Dashboard
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379" # Porta do Redis
      - "8001:8001" # Porta do RedisInsight (UI Visual)

  # --- 4. KAFKA (Mensageria) ---
  # O mesmo setup robusto do projeto anterior (KRaft)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,INTERNAL://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

  # Interface visual para o Kafka (Opcional, mas útil)
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9010:9000" # Mudei para 9099 para não conflitar com o MinIO
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka

volumes:
  oracle_data:
  minio_data: